FROM ubuntu
FROM ruby:2.3.1
#RUN apt-get update && \
#      apt-get -y install sudo

#sudo apt-get update
#sudo apt-get install git && git
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install git && git --version